import { useEffect } from 'react';
import { useLocation, Link as RouterLink } from 'react-router-dom';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Link from '@mui/material/Link';

const SECTIONS = [
  {
    id: 'acceptable-use',
    title: '1. Acceptable Use',
    content:
      'ChalkMind is designed for educational purposes only. You may use it to explore and learn about topics in science, history, technology, arts, and other educational domains. Do not request content that is harmful, illegal, violent, hateful, or sexually explicit.',
  },
  {
    id: 'ai-disclaimer',
    title: '2. AI Disclaimer',
    content:
      'All content generated by ChalkMind is produced by artificial intelligence (Google Gemini). AI-generated content may contain inaccuracies, omissions, or errors. It is not a substitute for professional education, advice, or expertise. Always verify important information with trusted, authoritative sources.',
  },
  {
    id: 'no-warranties',
    title: '3. No Warranties',
    content:
      'ChalkMind is provided "as is" without warranties of any kind, express or implied. We do not guarantee the accuracy, completeness, reliability, or availability of the service or its generated content.',
  },
  {
    id: 'user-responsibility',
    title: '4. User Responsibility',
    content:
      'You are responsible for how you use content generated by ChalkMind. Do not present AI-generated content as your own original work in academic or professional settings without proper disclosure.',
  },
  {
    id: 'privacy',
    title: '5. Privacy',
    content:
      'ChalkMind does not require user accounts and does not store personal data. Session data (topics, lessons) is ephemeral and not persisted after the session ends. Google Analytics may be used for anonymous usage metrics. reCAPTCHA is used for abuse prevention and is subject to Google\'s Privacy Policy and Terms of Service.',
  },
  {
    id: 'prohibited-use',
    title: '6. Prohibited Use',
    content:
      'The following uses are prohibited: attempting to bypass content safety filters, generating harmful or illegal content, automated scraping or bulk access, using the service for any unlawful purpose, or attempting to extract or reverse-engineer the underlying AI prompts or system instructions.',
  },
  {
    id: 'limitation-of-liability',
    title: '7. Limitation of Liability',
    content:
      'ChalkMind and its creators are not liable for any decisions, actions, or outcomes resulting from the use of AI-generated content. Use the service at your own risk.',
  },
  {
    id: 'changes',
    title: '8. Changes to Terms',
    content:
      'These terms may be updated at any time. Continued use of ChalkMind after changes constitutes acceptance of the updated terms.',
  },
];

export default function TermsPage() {
  const { hash } = useLocation();

  useEffect(() => {
    if (hash) {
      const el = document.getElementById(hash.slice(1));
      el?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [hash]);

  return (
    <Box
      sx={{
        minHeight: '100vh',
        background: '#0a0f0a',
        color: '#d1d5db',
        fontFamily: "'Lexend', sans-serif",
      }}
    >
      <Container maxWidth="md" sx={{ py: 6 }}>
        <Link
          component={RouterLink}
          to="/"
          underline="none"
          sx={{ color: '#6b7280', fontSize: '0.875rem', '&:hover': { color: '#2dd4bf' } }}
        >
          &larr; Back to ChalkMind
        </Link>

        <Typography
          variant="h3"
          sx={{
            mt: 4,
            mb: 1,
            fontWeight: 800,
            color: '#fff',
            letterSpacing: '-0.02em',
          }}
        >
          Terms of Use
        </Typography>
        <Typography variant="body2" sx={{ color: '#6b7280', mb: 5 }}>
          Last updated: March 2026
        </Typography>

        {SECTIONS.map((section) => (
          <Box key={section.id} id={section.id} sx={{ mb: 4 }}>
            <Typography
              variant="h6"
              sx={{ fontWeight: 700, color: '#e5e7eb', mb: 1 }}
            >
              {section.title}
            </Typography>
            <Typography
              variant="body2"
              sx={{ color: '#9ca3af', lineHeight: 1.8 }}
            >
              {section.content}
            </Typography>
          </Box>
        ))}

        <Box
          sx={{
            borderTop: '1px solid rgba(255,255,255,0.08)',
            mt: 6,
            pt: 4,
            textAlign: 'center',
          }}
        >
          <Typography variant="caption" sx={{ color: '#4b5563' }}>
            ChalkMind &middot; Built with Gemini AI &middot; Google Cloud
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
